# Example Azure DevOps pipeline with multiple examples embedded.

# The key concepts are explained here: https://learn.microsoft.com/azure/devops/pipelines/get-started/key-pipelines-concepts

# Using the default filename 'azure-pipelines.yml' will auto-register the pipeline in Azure DevOps.
# If you want to use a different filename, you will need to register the pipeline manually.

# When to run the pipeline.
trigger: 
- main


# Default pool for all stages and jobs
pool:
  # Use MS-hosted agents: https://learn.microsoft.com/azure/devops/pipelines/agents/hosted  
  # Installed Software: https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md
  vmImage: 'ubuntu-latest'  # other example: 'windows-latest'


variables:
- name: test-overwrite
  value: 'top level'
- name: azure_service_connection
  value: arm-example-conn


# Stages are the major divisions in a pipeline.
stages:
- template: templates\1-variables.yml
- template: templates\2-job-types.yml
- template: templates\3-agentless.yml
- template: templates\4-git.yml
- template: templates\5-azure-cli.yml