# This template demonstrates the job types.
#
# Key points for types:
# - Job usually depend on source code to build, test and publish.
# - Deployment usually depend on (pipeline) artifacts to deploy apps or infrastructure.


stages:
- stage: s2a
  displayName: Preperation (s2a)
  dependsOn: []
  jobs:
  - job: j1
    displayName: Create actifact
    steps:
    # Pipeline artifacts have to be unique, to support restartability, make the name unique each run.
    - script: |
        name="artifact1#$(System.JobAttempt)-$(Build.BuildId)"
        echo "##vso[task.setvariable variable=name;isOutput=true]$name"
        echo "created variable 'name=$name'"
      name: artifact
      displayName: Unique artifact
    
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        contents: 'README.md'
        targetFolder: $(Build.ArtifactStagingDirectory)

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: $(artifact.name)
      displayName: Publish artifact

- stage: s2b
  displayName: Job-types (s2b)

  jobs:
  - job: j1
    displayName: Type-Job
    steps:
    # Jobs checkout source-code of the selected branch by default.
    # Jobs do not download pipline artifacts by default.
    
    # Note: restarting a job will point to the same commit in the branch!
    - script: echo 'Jobs checkout code' && ls -lr .
      displayName: 'Run a one-line script'

  - deployment: d2
    displayName: Type-Deployment
    # defaults depends on previous stage, otherwise explicit define using dependsOn: [s2a]
    
    variables:
      artifact_name: $[stageDependencies.s2a.j1.outputs['artifact.name']]

    # Type: Deployment is coupled to an environment, defined as a string.
    # Although it a string, it is linked to a Pipeline Environment.
    # The environment is defined in the pipeline, and can be configured in the UI.
    #
    # Configure the environment to:
    # - Approvals: Single or multiple groups/individuals who all must approve. (no order, nr of people)
    # - Branch Control: Limit access to specific branches (e.g. only from main/release) optionally check for Branch Policy.
    # - Exclusive Lock: block concurrent Stages in any other pipeline with a deployment to the same environment.
    # - Business Hours: Limit access within specified timeframe.
    environment: 'example-env1'
    strategy:
      runOnce:
        # preDeploy: initialize resources before the deployment starts.
        deploy:
          steps:
          # Deployments do NOT checkout code by default.
          # Deployments download (all) pipeline artifacts by default.
          - script: |
              echo "actifact_name: $(artifact_name)"
              ls -lr $(Pipeline.Workspace)
            displayName: 'Run a one-line script'
        # routeTraffic: update routing rules to send traffic to this version.
        # postRouteTraffic: monitor health after updated version
        # on:
        #  failure: perform a rollback to the previous version.
        #  success: clean-up actions.

